export interface ChatMessage {
  id: string;
  role: 'user' | 'assistant';
  content: string;
  timestamp: Date;
}

export const intakeQuestions: string[] = [
  "Hi, I'm Althea. I'll ask you a few questions to better understand your situation and help prepare a summary for your chosen provider.\n\nI am not a therapist and cannot diagnose or treat you. Your answers will only be shared with your provider after your approval.\n\nWhat brings you here today? In your own words, what would you like support with?",
  "Thank you for sharing that. How long have you been experiencing this?",
  "On a scale of 1 to 10, how much is this affecting your daily life right now?\n(1 = barely noticeable, 10 = severely impacting everything)",
  "Have you ever received a mental health diagnosis before? If yes, you can mention it — or say no if you haven't.",
  "Are you currently receiving any form of support — such as therapy, counseling, or coaching?",
  "Are you currently taking any medication for mental health? You can say 'no' or 'prefer not to say'.",
  "How has your sleep been recently? For example: difficulty falling asleep, waking early, sleeping too much, or normal.",
  "Have you noticed any changes in your appetite or eating habits lately?",
  "Have you been experiencing anxiety, worry, or feelings of panic? If so, how often?",
  "Have you been feeling low, sad, or losing interest in things you usually enjoy?",
  "Have you experienced significant stress or felt burned out recently?",
  "Have you had any thoughts of harming yourself or others? You can answer honestly — this helps your provider understand your situation.",
  "What is your preferred language for therapy sessions?",
  "Do you have any preferences for how you receive support — for example, individual therapy, online sessions, or a particular approach like CBT?",
];

export const mockFollowUpResponses: string[] = [
  "Thank you for sharing that with me. I've noted it down.",
  "Understood. I've recorded that.",
  "Thank you. That gives helpful context for your provider.",
  "I've noted that. Your provider will have more details during your first appointment.",
  "Noted. This helps your provider understand where you are right now.",
  "Understood. You can always update this with your provider later.",
  "Sleep is closely connected to mental wellbeing. I've recorded that.",
  "Thank you. I've noted your response.",
  "I've noted your experience with anxiety. Your provider will explore this further.",
  "I hear you. I've recorded this as part of your summary.",
  "Stress and burnout are very common. This will help your provider understand your needs.",
  "Thank you for your honesty. This is important for your provider to know.",
  "Noted. Your provider will try to accommodate your language preference.",
  "Thank you. Your provider will discuss what approaches might work best for you.",
];

export const crisisKeywords: string[] = [
  'suicide',
  'suicidal',
  'kill myself',
  'end my life',
  'want to die',
  'self-harm',
  'selfharm',
  'cutting myself',
  'hurt myself',
  'harm myself',
  'no reason to live',
  'better off dead',
  "can't go on",
  'cannot go on',
  'not worth living',
  'end it all',
  'take my life',
  'overdose',
];

export const mockIntakeSummary = `**Intake Summary — Prepared by Althea**

**Main concern:** Anxiety and low mood, affecting study and social life.

**Duration:** Approximately 3 months.

**Severity:** 7 out of 10 — significantly impacting daily functioning.

**Previous diagnosis:** None reported.

**Current treatment:** None.

**Medication:** None.

**Sleep:** Difficulty falling asleep, waking early.

**Appetite:** Reduced appetite, some weight loss.

**Anxiety symptoms:** Frequent worry, occasional panic feelings.

**Mood:** Persistent low mood, reduced motivation.

**Stress/burnout:** High stress related to academic pressure.

**Safety:** No thoughts of self-harm reported at this time.

**Preferred language:** English.

**Therapy preferences:** Individual therapy, open to online sessions.

---
*This summary was generated by Althea and reviewed by the patient. It is a starting point for your provider — not a diagnosis. Your provider may ask additional questions during your first appointment.*`;
